version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_DB: world-db
      POSTGRES_USER: world
      POSTGRES_PASSWORD: world123

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "9090:8080"